### ISSUE TITLE
Statement syntax error when running the plugin

### ISSUE THREAD

**Issue by aviral-batra** [HEmile/obsidian-neo4j-graph-view#10]
I tried the plugin on one of my vaults and it worked perfectly, but on this vault there seems to be a problem.

Here is the short version - I've included the entire error below if you need.
```
Traceback (most recent call last):
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\__init__.py", line 450, in acquire
    cx = self._free_list.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aviral\AppData\Local\Temp\pythonShellFile8233150079.py", line 1, in <module>
    from smdc.stream import main;main();
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\smdc\stream.py", line 164, in main
    graph, tags = convert(args)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\smdc\convert.py", line 9, in convert
    return FORMAT_TYPES[args.output_format].write(notes, args)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\smdc\format\neo4j.py", line 61, in write
    raise e

# lot more lines here

py2neo.database.work.ClientError: [Statement.SyntaxError] Invalid input ')': expected whitespace, comment or a label name (line 3, column 1 (offset: 48))

") ON (n.name)"
```

long version:

```
ncaught Error: 
  0%|          | 0/424 [00:00<?, ?it/s]
 32%|###1      | 134/424 [00:00<00:00, 1339.73it/s]
 54%|#####3    | 227/424 [00:00<00:00, 1174.47it/s]
 99%|#########9| 421/424 [00:00<00:00, 1329.44it/s]
100%|##########| 424/424 [00:00<00:00, 1394.74it/s]

  0%|          | 0/422 [00:00<?, ?it/s]
100%|##########| 422/422 [00:00<00:00, 13188.26it/s]

  0%|          | 0/422 [00:00<?, ?it/s]
 51%|#####1    | 216/422 [00:01<00:01, 158.94it/s]
100%|##########| 422/422 [00:01<00:00, 300.36it/s]

  0%|          | 0/70 [00:00<?, ?it/s]
  1%|1         | 1/70 [00:00<01:05,  1.06it/s]
  3%|2         | 2/70 [00:01<00:47,  1.44it/s]
  4%|4         | 3/70 [00:01<00:36,  1.81it/s]
  7%|7         | 5/70 [00:01<00:26,  2.47it/s]
 10%|#         | 7/70 [00:01<00:20,  3.09it/s]
 13%|#2        | 9/70 [00:01<00:15,  3.98it/s]
 17%|#7        | 12/70 [00:02<00:11,  5.16it/s]
 20%|##        | 14/70 [00:02<00:09,  5.92it/s]
 23%|##2       | 16/70 [00:02<00:07,  6.95it/s]
 26%|##5       | 18/70 [00:02<00:06,  7.69it/s]
 29%|##8       | 20/70 [00:02<00:05,  9.08it/s]
 31%|###1      | 22/70 [00:02<00:04, 10.71it/s]
 34%|###4      | 24/70 [00:02<00:03, 12.17it/s]
 37%|###7      | 26/70 [00:03<00:03, 13.40it/s]
 40%|####      | 28/70 [00:03<00:03, 13.77it/s]
 43%|####2     | 30/70 [00:03<00:02, 14.15it/s]
 46%|####5     | 32/70 [00:03<00:02, 14.38it/s]
 49%|####8     | 34/70 [00:03<00:02, 14.51it/s]
 51%|#####1    | 36/70 [00:03<00:02, 15.16it/s]
 54%|#####4    | 38/70 [00:03<00:01, 16.35it/s]
 59%|#####8    | 41/70 [00:03<00:01, 17.09it/s]
 61%|######1   | 43/70 [00:04<00:01, 15.18it/s]
 64%|######4   | 45/70 [00:04<00:01, 12.99it/s]
 69%|######8   | 48/70 [00:04<00:01, 14.58it/s]
 73%|#######2  | 51/70 [00:04<00:01, 14.79it/s]
 76%|#######5  | 53/70 [00:04<00:01, 15.00it/s]
 79%|#######8  | 55/70 [00:04<00:01, 14.61it/s]
 81%|########1 | 57/70 [00:05<00:00, 15.38it/s]
 81%|########1 | 57/70 [00:05<00:01, 11.11it/s]
Traceback (most recent call last):
  File "C:\Users\Aviral\AppData\Local\Temp\pythonShellFile4767339406.py", line 1, in <module>
    from smdc.stream import main;main();
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\smdc\stream.py", line 164, in main
    graph, tags = convert(args)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\smdc\convert.py", line 9, in convert
    return FORMAT_TYPES[args.output_format].write(notes, args)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\smdc\format\neo4j.py", line 110, in write
    create_index(g, tag)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\smdc\format\neo4j.py", line 42, in create_index
    graph.run(f"CREATE INDEX index_{prop}_{tag} IF NOT EXISTS FOR (n:{tag}) ON (n.{prop})")
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\database\__init__.py", line 709, in run
    return self.auto().run(cypher, parameters, **kwparameters)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\database\work.py", line 127, in run
    result = self._connector.auto_run(self.graph.name, cypher, parameters,
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\__init__.py", line 936, in auto_run
    result = cx.auto_run(graph_name, cypher, parameters, readonly=readonly)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\bolt.py", line 673, in auto_run
    result.buffer()
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\bolt.py", line 949, in buffer
    self.__cx.sync(self)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\bolt.py", line 516, in sync
    self._audit(result)
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\bolt.py", line 626, in _audit
    task.audit()
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\bolt.py", line 883, in audit
    item.audit()
  File "C:\Users\Aviral\AppData\Roaming\Python\Python39\site-packages\py2neo\client\bolt.py", line 1062, in audit
    raise self._failure
py2neo.database.work.ClientError: [Statement.SyntaxError] Invalid input ')': expected whitespace, comment or a label name (line 3, column 1 (offset: 48))

") ON (n.name)"

 ^

    at PythonShell.parseError (eval at <anonymous> (app.js:1), <anonymous>:492:21)
    at terminateIfNeeded (eval at <anonymous> (app.js:1), <anonymous>:368:32)
    at ChildProcess.eval (eval at <anonymous> (app.js:1), <anonymous>:360:13)
    at ChildProcess.emit (events.js:315)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275)
PythonShellError @ index.js:49
parseError @ index.js:271
terminateIfNeeded @ index.js:146
eval @ index.js:138
emit @ events.js:315
ChildProcess._handle.onexit @ internal/child_process.js:275
```

**Comment by HEmile** [comment]
It looks like you have a tag somewhere that my parser isn't able to handle. I just pushed a fix for the Python package that should prevent this crash. It should print a warning in the terminal with the tag that caused it. Could you share this?

**Comment by corode** [comment]
Hmm. I downloaded the plugin again and ran it again on the problematic vault, but nothing is coming up on the console. 

Looking at the commit, it should print, as you said, so it seems like the error isn't being thrown now. Or in the last hour I've messed with the problematic link and it's no longer problematic.

Based on the error it looks like it was a bracket (but looking at my tags, I don't have any with brackets in them). I'm very confused now that it's not popping up.

**Comment by corode** [comment]
Whoops, accidentally closed the issue

**Comment by corode** [comment]
I noticed that there is an unknown process being called related to main.ts:

```typescript
// Use this for debugging
// console.log(stdout);
console.log(stderr);
let options = {
args: ['--input', this.path,  '--password', this.settings.password] // unknown process marked here
};
```

I have little knowledge of typescript but perhaps this has something to do with why it is not printing?

**Comment by HEmile** [comment]
Ah, I made a mistake here: The plugin won't print the error because it's not in debug mode, haha. I'll look into this soon. But indeed the vault should no longer be problematic because I now simply skip the error.

**Comment by corode** [comment]
I ran smdc on command line and it returned ```Warning: Could not create index for```

It didn't print anything after the warning!

**Comment by HEmile** [comment]
Thanks! But, huh. As in, it didn't print any name there? Then it's somehow recognizing "# " as a tag...

**Comment by HEmile** [comment]
I'm not using the converter anymore, so we can close this.
